############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Workshops"
url = "/workshops/"
weight = 2

[[main]]
name = "Blog"
url = "/blog/"
weight = 3

[[main]]
name = "About"
hasChildren = true
weight = 4

[[main]]
parent = "About"
name = "About Open Neuromorphic"
url = "/about/"
weight = 1

[[main]]
parent = "About"
name = "Getting Involved"
url = "/getting-involved/"
weight = 2

[[main]]
parent = "About"
name = "Team"
url = "/team/"
weight = 3

[[main]]
parent = "About"
name = "Contributors"
url = "/contributors/"
weight = 5

# footer menu
[[footer]]
name = "Quick Links"
hasChildren = true

[[footer]]
parent = "Quick Links"
name = "ONM Team"
url = "/team/"
weight = 2

[[footer]]
parent = "Quick Links"
name = "Join Our Discord"
url = "https://discord.gg/C9bzWgNmqk"
weight = 3

[[footer]]
parent = "Quick Links"
name = "How to Get Involved"
url = "/getting-involved/"
weight = 1



