baseurl = "https://open-neuromorphic.github.io"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "pink"
  showMenuItems = 5
  fullWidthTheme = true
  centerTheme = true
  favicon = "img/ONM-logo.png"

[languages]
  [languages.en]
    title = "Open Neuromorphic"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Open Neuromorphic"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "resources"
        name = "Resources"
        url = "/resources"
		weight = 1
      [[languages.en.menu.main]]
        identifier = "team"
        name = "Team"
        url = "/team"
		weight = 2
      [[languages.en.menu.main]]
        identifier = "opportunities"
        name = "Opportunities"
        url = "/opportunities"
		weight = 3
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
		weight = 4
